// client/src/pages/freelancer/mockData.js
// Centralized mock data for all freelancer pages

export const FREELANCER = {
  name: 'Aditya Singh',
  firstName: 'Aditya',
  role: 'Video Editor',
  avatar: 'AS',
  totalEarnings: 124560,
  completeness: 80,
  skills: ['Video Editing', 'Color Grading', 'Motion Graphics', 'Thumbnail Design'],
  hourlyRate: 850,
  rating: 4.9,
  reviewCount: 34,
  location: 'Delhi, India',
  bio: 'Professional video editor with 4+ years of experience in YouTube content, travel vlogs, and branded content.',
  onlineStatus: true,
}

export const PROJECTS = [
  {
    id: '1',
    title: '24 Hours Surviving in Delhi',
    client: 'Rohit Verma',
    clientAvatar: 'RV',
    category: 'Video Editing',
    progress: 60,
    dueDate: '20 May 2024',
    dueDaysLeft: 3,
    status: 'In Progress',
    budget: 25000,
    thumbnail: null,
    color: '#4540C8',
  },
  {
    id: '2',
    title: 'Travel Vlog: Himachal Series',
    client: 'Ankit Verma',
    clientAvatar: 'AV',
    category: 'Color Grading',
    progress: 40,
    dueDate: '22 May 2024',
    dueDaysLeft: 5,
    status: 'In Progress',
    budget: 18000,
    thumbnail: null,
    color: '#1D9E75',
  },
  {
    id: '3',
    title: 'Mini Documentary Project',
    client: 'Meera Kapoor',
    clientAvatar: 'MK',
    category: 'Motion Graphics',
    progress: 75,
    dueDate: '27 May 2024',
    dueDaysLeft: 10,
    status: 'In Progress',
    budget: 35000,
    thumbnail: null,
    color: '#F59E0B',
  },
  {
    id: '4',
    title: 'YouTube Thumbnails Pack',
    client: 'Akash Tiwari',
    clientAvatar: 'AT',
    category: 'Thumbnail Design',
    progress: 30,
    dueDate: '28 May 2024',
    dueDaysLeft: 11,
    status: 'In Progress',
    budget: 8000,
    thumbnail: null,
    color: '#EF4444',
  },
]

export const COMPLETED_PROJECTS = [
  {
    id: '5',
    title: 'Brand Intro Animation',
    client: 'Priya Sharma',
    clientAvatar: 'PS',
    category: 'Motion Graphics',
    progress: 100,
    dueDate: '10 Apr 2024',
    status: 'Completed',
    budget: 22000,
  },
  {
    id: '6',
    title: 'Podcast Editing — 12 Episodes',
    client: 'Rahul Nair',
    clientAvatar: 'RN',
    category: 'Video Editing',
    progress: 100,
    dueDate: '2 Apr 2024',
    status: 'Completed',
    budget: 15000,
  },
]

export const OPPORTUNITIES = [
  {
    id: '1',
    title: 'Editing for Travel Series (5 Episodes)',
    category: 'Video Editing',
    categoryIcon: '🎬',
    tags: ['Video Editing', 'Travel'],
    budgetMin: 15000,
    budgetMax: 25000,
    experience: 'Intermediate',
    postedAgo: '2 hours ago',
    clientName: 'Ravi Productions',
    description: 'Looking for an experienced video editor for a 5-episode travel series. Must have experience with color grading.',
  },
  {
    id: '2',
    title: 'Social Media Reels Editor',
    category: 'Video Editing',
    categoryIcon: '▶️',
    tags: ['Video Editing', 'Reels'],
    budgetMin: 8000,
    budgetMax: 12000,
    experience: 'Beginner',
    postedAgo: '5 hours ago',
    clientName: 'DigitalBrand Co.',
    description: 'Need a fast editor for Instagram Reels. 3–5 videos per week, quick turnaround required.',
  },
  {
    id: '3',
    title: 'Thumbnail Designer for YouTube Channel',
    category: 'Thumbnail Design',
    categoryIcon: '🖼️',
    tags: ['Thumbnail', 'YouTube'],
    budgetMin: 2000,
    budgetMax: 4000,
    experience: 'Beginner',
    postedAgo: '1 day ago',
    clientName: 'Tech Talks India',
    description: 'Consistent thumbnail style needed for a tech education YouTube channel. 8–10 thumbnails per month.',
  },
  {
    id: '4',
    title: 'Motion Graphics for Product Launch',
    category: 'Motion Graphics',
    categoryIcon: '✨',
    tags: ['Motion Graphics', 'After Effects'],
    budgetMin: 30000,
    budgetMax: 50000,
    experience: 'Expert',
    postedAgo: '2 days ago',
    clientName: 'StartupWave',
    description: 'High-quality motion graphics required for a D2C brand product launch campaign on YouTube.',
  },
  {
    id: '5',
    title: 'Color Grade Wedding Highlight Reel',
    category: 'Color Grading',
    categoryIcon: '🎨',
    tags: ['Color Grading', 'Wedding'],
    budgetMin: 12000,
    budgetMax: 18000,
    experience: 'Intermediate',
    postedAgo: '3 days ago',
    clientName: 'Memories Studio',
    description: 'Professional color grading needed for a wedding highlight reel. LUTs and cinematic look preferred.',
  },
]

export const TASKS = [
  {
    id: '1',
    title: 'Rough Cut Review',
    project: '24 Hours Surviving in Delhi',
    client: 'Rohit Verma',
    dueDate: 'Today',
    dueDateRaw: new Date(),
    priority: 'High',
    status: 'Pending',
    projectId: '1',
  },
  {
    id: '2',
    title: 'Color Grading',
    project: 'Travel Vlog: Himachal Series',
    client: 'Ankit Verma',
    dueDate: '21 May',
    dueDateRaw: new Date(Date.now() + 86400000),
    priority: 'High',
    status: 'In Progress',
    projectId: '2',
  },
  {
    id: '3',
    title: 'Thumbnail Concepts',
    project: 'Mini Documentary Project',
    client: 'Meera Kapoor',
    dueDate: '22 May',
    dueDateRaw: new Date(Date.now() + 2 * 86400000),
    priority: 'Medium',
    status: 'Pending',
    projectId: '3',
  },
  {
    id: '4',
    title: 'Final Export & Delivery',
    project: '24 Hours Surviving in Delhi',
    client: 'Rohit Verma',
    dueDate: '23 May',
    dueDateRaw: new Date(Date.now() + 3 * 86400000),
    priority: 'High',
    status: 'Pending',
    projectId: '1',
  },
  {
    id: '5',
    title: 'Sound Design Review',
    project: 'Mini Documentary Project',
    client: 'Meera Kapoor',
    dueDate: '25 May',
    dueDateRaw: new Date(Date.now() + 5 * 86400000),
    priority: 'Low',
    status: 'Pending',
    projectId: '3',
  },
  {
    id: '6',
    title: 'Pack Final Thumbnails (10x)',
    project: 'YouTube Thumbnails Pack',
    client: 'Akash Tiwari',
    dueDate: '27 May',
    dueDateRaw: new Date(Date.now() + 7 * 86400000),
    priority: 'Medium',
    status: 'Pending',
    projectId: '4',
  },
]

export const EARNINGS_CHART = [
  { month: 'Apr 21', amount: 42000 },
  { month: 'Apr 28', amount: 58000 },
  { month: 'May 5',  amount: 51000 },
  { month: 'May 12', amount: 78000 },
  { month: 'May 19', amount: 124560 },
]

export const MONTHLY_EARNINGS = [
  { month: 'Jan', amount: 32000 },
  { month: 'Feb', amount: 28000 },
  { month: 'Mar', amount: 45000 },
  { month: 'Apr', amount: 58000 },
  { month: 'May', amount: 124560 },
]

export const REVIEWS = [
  {
    id: '1',
    reviewer: 'Rohit Verma',
    reviewerAvatar: 'RV',
    project: '24 Hours Surviving in Delhi',
    rating: 5.0,
    text: 'Amazing work! Delivered high quality edit and understood the vision perfectly.',
    date: '15 May 2024',
  },
  {
    id: '2',
    reviewer: 'Meera Kapoor',
    reviewerAvatar: 'MK',
    project: 'Mini Documentary Project',
    rating: 4.8,
    text: 'Very professional and creative. Color grading was exactly what we needed.',
    date: '10 May 2024',
  },
  {
    id: '3',
    reviewer: 'Priya Sharma',
    reviewerAvatar: 'PS',
    project: 'Brand Intro Animation',
    rating: 5.0,
    text: 'Exceeded expectations. Motion graphics were top-notch and delivered on time!',
    date: '1 May 2024',
  },
  {
    id: '4',
    reviewer: 'Rahul Nair',
    reviewerAvatar: 'RN',
    project: 'Podcast Editing',
    rating: 4.7,
    text: 'Clean, crisp audio edits. Will definitely hire again for future episodes.',
    date: '8 Apr 2024',
  },
]

export const PROPOSALS = [
  {
    id: '1',
    title: 'YouTube Travel Vlog Series (10 Episodes)',
    client: 'Wanderlust India',
    budgetMin: 40000,
    budgetMax: 60000,
    proposedRate: 48000,
    status: 'pending',
    submittedOn: '15 May 2024',
    coverLetter: 'I have extensive experience editing travel vlogs with cinematic color grades...',
  },
  {
    id: '2',
    title: 'Corporate Brand Film Edit',
    client: 'TechVentures Pvt Ltd',
    budgetMin: 30000,
    budgetMax: 50000,
    proposedRate: 38000,
    status: 'accepted',
    submittedOn: '10 May 2024',
    coverLetter: 'My portfolio includes several corporate brand films for funded startups...',
  },
  {
    id: '3',
    title: 'Monthly Reels Package (20 reels)',
    client: 'FashionForward',
    budgetMin: 15000,
    budgetMax: 20000,
    proposedRate: 17500,
    status: 'rejected',
    submittedOn: '5 May 2024',
    coverLetter: 'I specialize in fast-paced reels with trending transitions and effects...',
  },
  {
    id: '4',
    title: 'Documentary: Startup Stories Season 2',
    client: 'IndiaMakers',
    budgetMin: 80000,
    budgetMax: 120000,
    proposedRate: 95000,
    status: 'pending',
    submittedOn: '18 May 2024',
    coverLetter: 'I am passionate about documentary storytelling and have worked on...',
  },
]

export const PORTFOLIO_ITEMS = [
  {
    id: '1',
    title: 'Travel Vlog: Leh Ladakh Series',
    description: 'Cinematic travel vlog with custom color grade and motion titles.',
    category: 'Video Editing',
    thumbnail: null,
    color: '#4540C8',
    views: 120000,
    likes: 4800,
  },
  {
    id: '2',
    title: 'Brand Identity Animation',
    description: 'Full logo reveal and brand identity motion graphics package.',
    category: 'Motion Graphics',
    thumbnail: null,
    color: '#1D9E75',
    views: 45000,
    likes: 2100,
  },
  {
    id: '3',
    title: 'YouTube Thumbnails — Tech Channel',
    description: '50+ thumbnails designed for a tech education channel, consistent style.',
    category: 'Thumbnail Design',
    thumbnail: null,
    color: '#F59E0B',
    views: 800000,
    likes: 32000,
  },
  {
    id: '4',
    title: 'Wedding Highlight — Rajasthan',
    description: 'Cinematic wedding highlight with color grading and music sync.',
    category: 'Color Grading',
    thumbnail: null,
    color: '#EF4444',
    views: 28000,
    likes: 1200,
  },
]

export const RESOURCES = [
  {
    id: '1',
    title: 'How to Price Your Freelance Services in India',
    category: 'Guide',
    readTime: '8 min read',
    description: 'A comprehensive guide to setting competitive rates as a freelancer in the Indian creator economy.',
    icon: '📖',
    color: '#4540C8',
  },
  {
    id: '2',
    title: 'Freelance Contract Template',
    category: 'Template',
    readTime: 'Download',
    description: 'A professional contract template for freelance video and creative work projects.',
    icon: '📄',
    color: '#1D9E75',
  },
  {
    id: '3',
    title: 'GST for Freelancers: Everything You Need to Know',
    category: 'Legal',
    readTime: '12 min read',
    description: 'Tax filing, GST registration, and invoicing guide for Indian freelancers.',
    icon: '⚖️',
    color: '#F59E0B',
  },
  {
    id: '4',
    title: 'Building a Winning Proposal',
    category: 'Guide',
    readTime: '5 min read',
    description: 'Tips and templates to write proposals that win more clients from the marketplace.',
    icon: '💡',
    color: '#9B7FD8',
  },
  {
    id: '5',
    title: 'Video Export Settings Cheat Sheet',
    category: 'Template',
    readTime: 'Download',
    description: 'Optimal export settings for YouTube, Instagram, and client delivery.',
    icon: '🎬',
    color: '#EF4444',
  },
  {
    id: '6',
    title: 'Managing Multiple Clients Without Burnout',
    category: 'Guide',
    readTime: '6 min read',
    description: 'Productivity and workflow tips for freelancers managing multiple projects.',
    icon: '🧘',
    color: '#1D9E75',
  },
]

export const TIME_LOGS = [
  { id: '1', project: '24 Hours Surviving in Delhi', task: 'Rough Cut', date: 'Today', hours: 3.5, billable: true },
  { id: '2', project: 'Travel Vlog: Himachal Series', task: 'Color Grading', date: 'Yesterday', hours: 5.0, billable: true },
  { id: '3', project: 'Mini Documentary Project', task: 'Motion Graphics', date: '20 May', hours: 4.5, billable: true },
  { id: '4', project: 'YouTube Thumbnails Pack', task: 'Design Concepts', date: '19 May', hours: 2.0, billable: true },
  { id: '5', project: '24 Hours Surviving in Delhi', task: 'Audio Sync', date: '18 May', hours: 1.5, billable: false },
  { id: '6', project: 'Mini Documentary Project', task: 'Script Review', date: '17 May', hours: 1.0, billable: false },
]

export const MESSAGES = [
  {
    id: '1',
    contact: 'Rohit Verma',
    contactAvatar: 'RV',
    project: '24 Hours Surviving in Delhi',
    lastMessage: 'Can you share the rough cut by tonight?',
    time: '2m ago',
    unread: 2,
    online: true,
    messages: [
      { from: 'them', text: 'Hey! How is the edit going?', time: '10:00 AM' },
      { from: 'me',   text: 'Going well! About 60% done', time: '10:05 AM' },
      { from: 'them', text: 'Can you share the rough cut by tonight?', time: '10:10 AM' },
    ],
  },
  {
    id: '2',
    contact: 'Ankit Verma',
    contactAvatar: 'AV',
    project: 'Travel Vlog: Himachal Series',
    lastMessage: 'Loved the color grade! Please send final.',
    time: '1h ago',
    unread: 0,
    online: false,
    messages: [
      { from: 'them', text: 'How does the color grade look?', time: '9:00 AM' },
      { from: 'me',   text: 'Just sent you a preview!', time: '9:15 AM' },
      { from: 'them', text: 'Loved the color grade! Please send final.', time: '9:30 AM' },
    ],
  },
  {
    id: '3',
    contact: 'Meera Kapoor',
    contactAvatar: 'MK',
    project: 'Mini Documentary Project',
    lastMessage: 'Please add subtitles to the interview section',
    time: '3h ago',
    unread: 1,
    online: true,
    messages: [
      { from: 'them', text: 'Please add subtitles to the interview section', time: '8:00 AM' },
    ],
  },
]
